CREATE DATABASE IF NOT EXISTS `androidtv`;
use `androidtv`;

CREATE TABLE IF NOT EXISTS live (
  live_id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(500) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  source_url VARCHAR(500) NOT NULL,
  license_url VARCHAR(500) NOT NULL,
  PRIMARY KEY (live_id)
) ENGINE=InnoDB AUTO_INCREMENT=10;

CREATE TABLE IF NOT EXISTS epg (
  epg_id INT(11) NOT NULL AUTO_INCREMENT,
  service_id INT(11) NOT NULL,
  title VARCHAR(500) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  source_url VARCHAR(500) NOT NULL,
  license_url VARCHAR(500) NOT NULL,
  PRIMARY KEY (epg_id)
) ENGINE=InnoDB AUTO_INCREMENT=10;

CREATE TABLE IF NOT EXISTS vod (
  vod_id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(500) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  source_url VARCHAR(500) NOT NULL,
  license_url VARCHAR(500) NOT NULL,
  PRIMARY KEY (vod_id)
) ENGINE=InnoDB AUTO_INCREMENT=10;
